config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.create_comment, name='create_comment'),
]

users/urls.py
from django.urls import path
from users import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()

def get_post_pic_directory_path(instance, filename):
    return f'users/id{instance.author.id}/posts/{instance.id}/{filename}'

class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(
        blank=False, 
        null=False
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        to=User, 
        on_delete=models.CASCADE, 
        related_name='posts',
        verbose_name='Автор'
        )
    pic = models.ImageField(
        verbose_name='Картинка',
        upload_to=get_post_pic_directory_path,
        blank=True,
        null=True
        )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return f'{self.text}'
    
    def save(self, *args, **kwargs):
        if not self.id and self.pic:
            pic = self.pic
            self.pic = None
            super().save(*args, **kwargs)
            self.pic = pic
            super().save(update_fields=['pic'])
        else:
            super().save(*args, **kwargs)


class Comment(models.Model):
    author = models.ForeignKey(
        to=User, 
        on_delete=models.CASCADE, 
        related_name='comments',
        verbose_name='Автор'
        )
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    to_post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'A:{self.author.id} P:{self.to_post.id} {self.text}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


def get_user_directory_path(instance, filename):
    return f'users/id{instance.id}/photos/{filename}'


class User(AbstractUser):
    photo = models.ImageField(
        verbose_name='Аватар',
        upload_to=get_user_directory_path,
        blank=True,
        null=True,
        default='users/default/avatars/A.png'
    )

    def save(self, *args, **kwargs):
        if not self.id and self.photo:
            photo = self.photo
            self.photo = None
            super().save(*args, **kwargs)
            self.photo = photo
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

posts/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.TextInput(
            attrs={
        'class': 'form-control me-2',
        'placeholder': "Напишите комментарий",
        'rows': 1
    }
    )
    )
    class Meta:
        model = Comment
        fields = ['text']

users/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model


User = get_user_model()

class SignUpForm(forms.ModelForm):
    error_messages = {
        'no_password_confirmation': 'Пожалуйста подтвердите пароль',
        'password_mismatch': 'Пароли не совпадают',
    }

    password1 = forms.CharField(
        widget=forms.PasswordInput, 
        label='Пароль',
        strip=False,
        help_text='Пароль должен состоять из латинских символов, цифр или знаков @/./+/-/_'
        )
    password2 = forms.CharField(
        widget=forms.PasswordInput, 
        label='Повторите пароль',
        strip=False,
        )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username': 'Имя',
        }
        help_texts = {
            'username': 'Не более 150 символов. Допустима латиница , цифры или символы @/./+/-/_'
        }
        error_messages = {
            'username': {
                'unique': 'Пользователь с таким именем уже существует'
            }
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError(self.error_messages['no_password_confirmation'])
        
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(self.error_messages['password_mismatch'])
        
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))
        if commit:
            user.save()
        return user
    

class LoginForm(forms.Form):
    error_messages = {
        'invalid_credentials': 'Неверный логин или пароль'
    }

    username = forms.CharField(
        label='Имя',
        widget=forms.TextInput,
        help_text='Введите ваше имя'
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        help_text='Введите ваш пароль'
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError(self.error_messages['invalid_credentials'])
            cleaned_data['user'] = user
            
        return cleaned_data

posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm

from .models import Post


def home(request):
    posts = Post.objects.all()
    form = CommentForm()
    context = {
        'posts': posts,
        'form': form
    }
    return render(request, 'index.html', context=context)

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post, 'comment_form': CommentForm()})


def create_comment(request, post_id):
    next_page = request.POST.get('next_page') or request.GET.get('next', '/')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_post = Post.objects.get(pk=post_id)
            comment.author = request.user
            comment.save()
        else:
            print(form.errors)
        return redirect(next_page)
    else:
        return redirect(next_page)

users/views.py
from django.contrib import auth
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import LoginForm, SignUpForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get('user')
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'users/login.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'users/signup.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect(reverse('posts:home'))

posts/templates/posts/post_detail.html
{% extends "base.html" %}


{% block content %}
<!-- ПОСТ -->
  <div class="card p-3 m-3" style="width: 540px;">
    
    <div class="post-header">
      <div class="post-author-avatar d-flex align-items-center">
        <!-- Аватар -->
        <div class="author-avatar avatar me-2">
          <img class="rounded-circle" style="width: 40px; height: 40px;" src="{{ post.author.photo.url }}" alt="">
        </div>

        <!-- Юзернейм и статус -->
        <div class="post-author-info d-flex flex-column flex-grow-1 justify-content-center">
          <div class="post-author d-flex justify-content-between">          
            <h6 class="author-username mb-0 card-title">{{ post.author.username }}</h6>
            <small class="post-created-at mb-0 text-muted">{{ post.created_at }}</small>
          </div>
          <small class="text-muted">Модератор</small>
        </div>
      </div>

    <div class="post-body">
      <div class="mt-3">
        <h4 class="post-title">{{ post.title }}</h4>
        <p class="post-text">
        {{ post.text }}
        </p>
        
      </div>
    </div>

    <div class="post-footer">
      <div class="d-flex">
        <div class="d-flex justify-content-center align-items-center">
          
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill me-1" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
          </svg>
          <span class="likes-number me-2">38</span>
        </div>
        <div class="d-flex justify-content-center align-items-center">
          
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat me-1" viewBox="0 0 16 16">
            <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
          </svg>
          <span class="comments-number me-2">{{ post.comments.count }}</span>
        </div>
      </div>
    </div>
  </div>

<!-- КОММЕНТАРИИ -->

<div class="card p-3 mt-3">

  <h6 class="text-center mb-3">Комментарии</h6>
  <!-- Форма комментария -->
   <form action="{% url "posts:create_comment" post.id %}" method="post" class="add-comment">
    {% csrf_token %}
    <div class="comment-header">
      <div class="d-flex">
        <img class="rounded-circle me-1" style="width: 40px; height: 40px;" src="{{ user.photo.url }}" alt="">
        {{ comment_form.text }}
        <button type="submit" class="bg-transparent nav-link border-0">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
</svg>
        </button>
      </div>
   </form>

  {% for comment in post.comments.all %}
  <div class="comments-items mt-3">
    <div class="comment card p-2 mb-2">

      <div class="comment-header">
        <div class="comment-author-avatar d-flex align-items-center">
          <!-- Аватар -->
          <img class="rounded-circle me-1" style="width: 30px; height: 30px;" src="{{ comment.author.photo.url }}" alt="">

          <!-- Юзернейм и статус -->
          <div class="comment-author-info d-flex flex-column flex-grow-1 justify-content-center">
            <div class="comment-author d-flex justify-content-between">          
              <h6 class="author-username mb-0 card-title m-0" style="font-size: 14px;">{{ comment.author.username }}</h6>
              <small class="comment-created-at mb-0 text-muted fw-light" style="font-size: 12px;">{{ comment.created_at }}</small>
            </div>
            <small class="text-muted m-0" style="font-size: 12px;">Модератор</small>
          </div>
        </div>
      </div>

      <div class="comment-body">
        <div class="mt-1">
          <p class="comment-text">
          {{ comment.text }}
        </p>
        </div>
      </div>
    </div>

  </div>
  {% endfor %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="{% static "css/styles.css" %}" rel="stylesheet">
  {% block title %}
  {% endblock title %}
</head>

<body>
  <div class="body-container">
    {% include "includes/sidebar.html" %}

    <div class="content">
      <header>
        {% include "includes/nav.html" %}
        {% include "includes/accountnav.html" %}
        {% include "includes/usernav.html" %}
        {% include "includes/tagbar.html" %}
        
      </header>
      
      <main>
      {% block content %}
      {% endblock content %}
      </main>

    </div>
  </div>
</body>

<script src="{% static "js/posts.js" %}"></script>
</html>

templates/includes/accountnav.html
{% load static %}
<nav class="account-header">
  <img class="account-header-avatar" src="{{ user.photo.url }}">
  <div class="account-header-meta">
    <span class="account-header-user-username">{{ user.username }}</span>
    <span class="account-header-user-following">Following: 541</span>
    <span class="account-header-user-followers">Followers: 391</span>
    <span class="account-header-user-rank">Rank: Verified</span>
    <span class="account-header-user-date-joined">Joined: {{ user.date_joined }}</span>
    <span class="account-header-user-date-posts">Posts: {{ user.posts.count }}</span>
  </div>
  <div class="account-header-interactions">
    <div class="account-header-interactions-item">
      <button class="account-header-follow button">
        <span>Написать</span>
        <img src="{% static "svg/chat-dots.svg" %}" alt="">
      </button>
    </div>
    <div class="account-header-interactions-item">
      <button class="account-header-follow button">
        <span>Подписаться</span>
        <img src="{% static "svg/plus-square-fill.svg" %}" alt="">
      </button>
    </div>
  </div>
</nav>

templates/includes/nav.html
{% load static %}
<nav class="navigation-bar main-navigation-bar">
  <div class="navigation main-navigation">
    <div class="navigation-item">
      <span class="navigation-elem logo">VarChar</span>
    </div>
    <div class="navigation-item">
      <form action="." class="search-form" method="get">
        <input class="search-input" type="search" placeholder="Поиск...">
        <button class="search-button button" type="submit">
          <img src="{% static "svg/search.svg" %}" alt="">
        </button>
      </form>
    </div>
    <div class="navigation-item">
      <ul class="navigation-menu">
        <li class="navigation-menu-item">
          <a href="" class="navigation-link button-main-nav">Наварчарить</a>
        </li>
        <li class="navigation-menu-item">
          <a href="" class="navigation-link button-main-nav">Войти</a>
        </li>
      </ul>
    </div>
  </ul>
</nav>

templates/includes/post.html
{% load static %}
<div class="post-feed">

  <!-- ПОСТ -->
  {% for post in posts %}
  <div class="post">

    
    <div class="post-header-container">
      <img class="post-author-avatar" src="{% static "img/A.png" %}">
      <div class="post-header">
        <div class="post-author">
          <p class="post-author-username">{{ post.author }}</p>
          <p class="post-author-rank">Модератор</p>
        </div>
        <div class="post-date">
          <p class="post-date-published">{{ post.created_at }}</p>
        </div>
      </div>
      {% if post.author == request.user %}
      <button class="button edit-post">
        <img src="{% static "svg/highlighter.svg" %}" alt="">
      </button>
      <button class="button delete-post">
        <img src="{% static "svg/x-square.svg" %}" alt="">
      </button>
      {% endif %}
    </div>

    <div class="post-body">
      <p class="post-text">
        {{ post.text }}
      </p>
      <span class="post-updated-at">{{ post.updated_at }}</span>
    </div>

    <div class="post-footer">
      <ul class="post-stats">
        <li class="post-stats-item">
          <button onclick="likePost({{ post.id }})" id="like-{{ post.id }}" class="like button">
            <img class="post-stats-item-icon" src="{% static "svg/heart.svg" %}" alt="">  
          </button>
          <p class="post-likes">15</p>
        </li>
        <li class="post-stats-item">
          <button onclick="toggleComments({{ post.id }})" id="comments" class="comment button">
            <img class="post-stats-item-icon" src="{% static "svg/chat.svg" %}" alt="">  
          </button>
          <p class="post-comments">{{ post.comments.count }}</p>
        </li>
        <li class="post-stats-item">
          <button id="reposts" class="repost button">
            <img class="post-stats-item-icon" src="{% static "svg/check-circle.svg" %}" alt="">  
          </button>
          <p class="post-reposts">6</p>
        </li>
      </ul>
    </div>

    <!-- Блок комментариев -->
    <section class="comments-block" id="comment-section-to-{{ post.id }}">

      <!-- Форма добавления комментария -->
      <form class="add-comment-form" id="add-comment-form" action="">
        <input type="text" name="text" id="add-comment" placeholder="Напишите комментарий...">
        <button class="add-comment" type="submit">
          <img src="{% static "svg/send.svg" %}" alt="">
        </button> 
      </form>

      <!-- Комментарии -->
      
      <div class="post-comments-section" id="comments-section">

        <h4 class="comment-section-title">Комментарии</h4>
        <ul class="comment-list">

          {% for comment in post.comments.all %}
          <li class="comment-item">

            <div class="comment-header-container">
              <img class="comment-author-avatar" src="{% static "img/A.png" %}">
              <div class="comment-header">
                <div class="comment-author">
                  <p class="comment-author-username">{{ comment.author }}</p>
                  <p class="comment-author-rank">Модератор</p>
                </div>
                <div class="comment-date">
                  <p class="comment-date-published">{{ comment.updated_at }}</p>
                </div>
              </div>
            </div>

            <div class="comment-body">
              <p class="comment-text">
                {{ comment.text }}
              </p>
            </div>

            <ul class="comment-reaction-list">
              <li class="comment-reaction-item">
                <button onclick="likeComment()" id="like-comment" class="like-comment button">
                  <img class="post-stats-item-icon" src="{% static "svg/heart.svg" %}" alt="">  
                </button>
                <p class="post-likes">4</p>
              </li>
              <li class="comment-reaction-item">
                <button class="add-comment button" type="submit">
                  <img class="comment-reply-icon" src="{% static "svg/reply.svg" %}" alt="">
                </button>
              </li>

            </ul> <!-- конец-comment-reaction-list-->
          </li> <!-- конец-comment-item-->
          {% endfor %}

        </ul><!-- конец-comment-item-list-->
      </div>
    </section>
    
    <!-- комментарии (конец) -->

  </div>
{% endfor %}

templates/includes/sidebar.html
{% load static %}
<nav class="sidebar">
  <ul class="sidebar-navigation">
    <li class="sidebar-navigation-item">
      <img class="sidebar-icon" src="{% static "svg/house-door.svg" %}" alt="">
      <p>Home</p>
    </li>
    <li class="sidebar-navigation-item">
      <img class="sidebar-icon" src="{% static "svg/plus-circle-fill.svg" %}" alt="">
      <p>Add</p>
    </li>
  </ul>
</nav>

templates/includes/tagbar.html
<nav class="tag-panel">
    <ul class="tags-list">
        <li class="tag">Новости</li>
        <li class="tag">Кино</li>
        <li class="tag">Отношения</li>
        <li class="tag">Хобби</li>
        <li class="tag">Шоу-бизнес</li>
        <li class="tag">Погода</li>
        <li class="tag">Квартиры</li>
        <li class="tag">Аренда</li>
        <li class="tag">Юриспруденция</li>
        <li class="tag">Музыка</li>
        <li class="tag">Настроение</li>
    </ul>
</nav>

templates/includes/usernav.html
<nav class="user-navbar">
    <ul class="usernav-list">
      <li class="usernav-item active">
        <a class="usernav-link" href="/">Лента</a>
      </li>
      <li class="usernav-item">
        <a class="usernav-link" href="/">Аккаунт</a>
      </li>
      <li class="usernav-item">
        <a class="usernav-link" href="/">Избранное</a>
      </li>
      <li class="usernav-item">
        <a class="usernav-link" href="/">Статистика</a>
      </li>
    </ul>

</nav>

templates/index.html
{% extends "base.html" %}

{% block content %}
{% include "includes/post.html" %}
{% endblock content %}

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
</head>
<body>
    <form action=".">
        <input type="text">
    </form>
    
</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}
<title>Авторизация</title>
{% endblock title %}

{% block content %}
<section class="bg-light p-3 p-md-4 p-xl-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
        <div class="card border border-light-subtle rounded-4">
          <div class="card-body p-3 p-md-4 p-xl-5">
            <div class="row">
              <div class="col-12">
                <div class="mb-5">
                  <h2 class="h4 text-center">Войти</h2>
                </div>
              </div>
            </div>
            <form action="." method="POST">
            {% csrf_token %}

            <!-- Ошибки для всей формы -->
            {% if form.non_field_errors %}
              <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}

              <!-- Поле -->
              <div class="row gy-3 overflow-hidden">
                {% for field in form %}
                <div class="col-12">
                  {{ field.label_tag }}
                  <div class="form-floating mb-3">
                    {% if field.errors %}
                      {{ field|add_class:"form-control is-invalid"}}
                    {% else %}
                      {{ field|add_class:"form-control"}}
                    {% endif %}

                    <!-- Ошибки поля -->
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                    {% endfor %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  </div>  
                </div>
                {% endfor %}

                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn btn-lg bsb-btn-xl btn-success mt-3" type="submit">Войти</button>
                  </div>
                </div>
              </div>    
            </form>
            <div class="row mb-3">
              <div class="col-12">
                <hr class="mt-5 mb-4 border-secondary-subtle">
                <p class="m-0 text-secondary text-center">Нет аккаунта? <a href="{% url "users:signup" %}" class="link-primary text-success text-decoration-none">Зарегистрироваться</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}
<title>Регистрация</title>
{% endblock title %}

{% block content %}
<section class="bg-light p-3 p-md-4 p-xl-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
        <div class="card border border-light-subtle rounded-4">
          <div class="card-body p-3 p-md-4 p-xl-5">
            <div class="row">
              <div class="col-12">
                <div class="mb-5">
                  <h2 class="h4 text-center">Регистрация</h2>
                </div>
              </div>
            </div>
            <form action="." method="POST">
            {% csrf_token %}

            <!-- Ошибки для всей формы -->
            {% if form.non_field_errors %}
              <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}

              <!-- Поле -->
              <div class="row gy-3 overflow-hidden">
                {% for field in form %}
                <div class="col-12">
                  {{ field.label_tag }}
                  <div class="form-floating mb-3">
                    {% if field.errors %}
                      {{ field|add_class:"form-control is-invalid"}}
                    {% else %}
                      {{ field|add_class:"form-control"}}
                    {% endif %}

                    <!-- Ошибки поля -->
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                    {% endfor %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  </div>  
                </div>
                {% endfor %}

                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn btn-lg bsb-btn-xl btn-success mt-3" type="submit">Зарегистироваться</button>
                  </div>
                </div>
              </div>    
            </form>
            <div class="row mb-3">
              <div class="col-12">
                <hr class="mt-5 mb-4 border-secondary-subtle">
                <p class="m-0 text-secondary text-center">Уже зарегистированы? <a href="{% url "users:login" %}" class="link-primary text-success text-decoration-none">Войти</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}